version: '3.4'
services:
  # Prometheus - Se ejecuta en nodo Manager
  prometheus:
    image: jaweewo/prometheus-local:local
    #volumes:
    #  - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik

# Node Exporter de Prometheus --> 1 por cada nodo en servicios separados.
  master:
    image: jaweewo/node-exporter:local
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
      #- '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      #- '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname nodo master!
         - node.hostname == swarm-master
    networks:
      - traefik

  worker1:
    image: jaweewo/node-exporter:local
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname nodo worker
         - node.hostname == swarm-node1
    networks:
      - traefik


#FIN NODE EXPORTER


# cAdvisor --> Se ejecuta en cada nodo
#Inicio cAdvisor
  docker-master1:
    image: jaweewo/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-master
    networks:
      - traefik

  docker-worker1:
    image: jaweewo/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-node1
    networks:
      - traefik

### Fin cAdvisor

  grafana:
    image: jaweewo/grafana:local
    #logging:
    # driver: loki
      #options:
       # loki-url: "http://192.168.0.11:3100/loki/api/v1/push"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.jaweewo.com`)"
        - "traefik.http.routers.grafana.entrypoints=web"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  loki:
    image: jawewewo/loki:local
    ports:
      - "3100:3100"
    #volumes:
      #- $PWD/loki/loki-local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - traefik

  promtail:
    image: jaweewo/promtail:lates
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - traefik
    deploy:
      mode: global


networks:
  traefik:
    external: true
volumes:
  grafana-storage:
    external: true
