name: Docker Image CI test

on:
  push:
    branches: [ swarm ]
  pull_request:
    branches: [ swarm ]

jobs:

  build prometheus:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker build ./Builds/Prometheus --file Dockerfile --tag jaweewo/prometheus:$(date +%s)
      
      
