name: Docker Image CI

on:
  push:
    branches: [ swarm ]
  pull_request:
    branches: [ swarm ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@b74f2665a4a826412bdb4c355deb6fdc2e80d42b
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with:
        # Name of the Docker image
        image: jaweewo/grafana
        # Tags override for Docker image
        tags: test
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: # optional, default is Dockerfile
        # Directory to run `docker build` from, if not project root
        directory: Builds/Manifest
        # Docker registry username
        username: $ {{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: $ {{ secrets.DOCKER_PASSWORD }}

